//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateModel
    {
        public System.Guid DateId { get; set; }
        public string DateCode { get; set; }
        public Nullable<System.Guid> NguoiDatHen { get; set; }
        public Nullable<System.Guid> BacSiKham { get; set; }
        public Nullable<System.Guid> YTaXacNhan { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.Guid> PaymentStatus { get; set; }
        public Nullable<System.Guid> DateStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> Payment { get; set; }
    
        public virtual AccountModel AccountModel { get; set; }
        public virtual AccountModel AccountModel1 { get; set; }
        public virtual AccountModel AccountModel2 { get; set; }
    }
}
