//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationModel()
        {
            this.NotificationForAccounts = new HashSet<NotificationForAccount>();
            this.NotificationInRoleModels = new HashSet<NotificationInRoleModel>();
        }
    
        public System.Guid NotificationId { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationDetail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string NotificationLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationForAccount> NotificationForAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationInRoleModel> NotificationInRoleModels { get; set; }
    }
}
