//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationInRoleModel
    {
        public System.Guid NotificationInRoleModelId { get; set; }
        public Nullable<System.Guid> NotificationId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
    
        public virtual NotificationModel NotificationModel { get; set; }
        public virtual RolesModel RolesModel { get; set; }
    }
}
