//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageModel()
        {
            this.PageFunctionModels = new HashSet<PageFunctionModel>();
            this.PagePermissionModels = new HashSet<PagePermissionModel>();
        }
    
        public System.Guid PageId { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> MenuId { get; set; }
    
        public virtual MenuModel MenuModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageFunctionModel> PageFunctionModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagePermissionModel> PagePermissionModels { get; set; }
    }
}
