//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyPhongMachWibuEntities : DbContext
    {
        public QuanLyPhongMachWibuEntities()
            : base("name=QuanLyPhongMachWibuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountInRoleModel> AccountInRoleModels { get; set; }
        public virtual DbSet<AccountModel> AccountModels { get; set; }
        public virtual DbSet<AccountRecoveryTokenModel> AccountRecoveryTokenModels { get; set; }
        public virtual DbSet<CatalogModel> CatalogModels { get; set; }
        public virtual DbSet<CatalogTypeModel> CatalogTypeModels { get; set; }
        public virtual DbSet<ChangeDataLogModel> ChangeDataLogModels { get; set; }
        public virtual DbSet<CityModel> CityModels { get; set; }
        public virtual DbSet<DateModel> DateModels { get; set; }
        public virtual DbSet<DescriptionDetailModel> DescriptionDetailModels { get; set; }
        public virtual DbSet<DescriptionIllnessModel> DescriptionIllnessModels { get; set; }
        public virtual DbSet<DescriptionModel> DescriptionModels { get; set; }
        public virtual DbSet<DistrictModel> DistrictModels { get; set; }
        public virtual DbSet<DistrictStreetModel> DistrictStreetModels { get; set; }
        public virtual DbSet<DistrictWardModel> DistrictWardModels { get; set; }
        public virtual DbSet<FunctionModel> FunctionModels { get; set; }
        public virtual DbSet<IllnessModel> IllnessModels { get; set; }
        public virtual DbSet<IngredientModel> IngredientModels { get; set; }
        public virtual DbSet<MedicineCompoundModel> MedicineCompoundModels { get; set; }
        public virtual DbSet<MedicineModel> MedicineModels { get; set; }
        public virtual DbSet<MedicineProvideModel> MedicineProvideModels { get; set; }
        public virtual DbSet<MenuModel> MenuModels { get; set; }
        public virtual DbSet<PageFunctionModel> PageFunctionModels { get; set; }
        public virtual DbSet<PageModel> PageModels { get; set; }
        public virtual DbSet<PagePermissionModel> PagePermissionModels { get; set; }
        public virtual DbSet<ProviderModel> ProviderModels { get; set; }
        public virtual DbSet<RolesModel> RolesModels { get; set; }
        public virtual DbSet<StreetModel> StreetModels { get; set; }
        public virtual DbSet<UsersModel> UsersModels { get; set; }
        public virtual DbSet<WardModel> WardModels { get; set; }
        public virtual DbSet<WarehouseModel> WarehouseModels { get; set; }
    }
}
