//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnjuAihara.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseModel
    {
        public System.Guid WarehouseId { get; set; }
        public Nullable<System.Guid> MedicineProviderId { get; set; }
        public Nullable<decimal> BoughtQuantity { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string BoughtPrice { get; set; }
        public Nullable<decimal> InstockQuantity { get; set; }
        public Nullable<System.DateTime> BoughtDate { get; set; }
    
        public virtual MedicineProvideModel MedicineProvideModel { get; set; }
    }
}
