//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGeneration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescriptionModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DescriptionModel()
        {
            this.DescriptionDetailModels = new HashSet<DescriptionDetailModel>();
            this.DescriptionIllnessModels = new HashSet<DescriptionIllnessModel>();
        }
    
        public System.Guid DescriptionId { get; set; }
        public string DescriptionCode { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescriptionDetailModel> DescriptionDetailModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescriptionIllnessModel> DescriptionIllnessModels { get; set; }
        public virtual AccountModel AccountModel { get; set; }
    }
}
