//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGeneration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictModel()
        {
            this.DistrictStreetModels = new HashSet<DistrictStreetModel>();
            this.DistrictWardModels = new HashSet<DistrictWardModel>();
        }
    
        public System.Guid DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string DonViHanhChinh { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
    
        public virtual CityModel CityModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictStreetModel> DistrictStreetModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictWardModel> DistrictWardModels { get; set; }
    }
}
