//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGeneration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineProvideModel
    {
        public System.Guid MedicineProvideId { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.Guid> MedicineId { get; set; }
        public Nullable<decimal> BoughtQuantity { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<decimal> BoughtPrice { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<decimal> InstockQuantity { get; set; }
    
        public virtual MedicineModel MedicineModel { get; set; }
        public virtual ProviderModel ProviderModel { get; set; }
    }
}
